[[main]]
  name = ">Whoami"
  url = "/about/"
  weight = 1

[[main]]
  name = "IT и технологии"
  url = "/categories/it-%D0%B8-%D1%82%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D0%B8/"
  weight = 2

[[main]]
  name = "Жиза"
  url = "/categories/%D0%B6%D0%B8%D0%B7%D0%B0/"
  weight = 3

[[main]]
  name = "Незапатентованные мысли"
  url = "/categories/%D0%BD%D0%B5%D0%B7%D0%B0%D0%BF%D0%B0%D1%82%D0%B5%D0%BD%D1%82%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BC%D1%8B%D1%81%D0%BB%D0%B8/"
  weight = 4

[[main]]
  name = "Биохакинг"
  url = "/categories/%D0%BE%D1%81%D0%BE%D0%B7%D0%BD%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D0%BD%D1%8B/"
  weight = 5

